import { useState } from "react";
import { motion } from "framer-motion";
import { jsPDF } from "jspdf";
import {
  AlertCircle,
  CheckCircle2,
  Copy,
  Download,
  FileText,
  Loader2,
} from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import type {
  ExecutiveReport,
  KpiCard,
  VisualDashboard,
  WorkspaceParams,
} from "@/api";
import { fetchReportWithNarrative } from "@/api";

// ============================================================
// Props
// ============================================================

interface ReportViewProps {
  productId: string;
  competitorId: string;
  startDate: string;
  endDate: string;
  productName: string;
  dashboard: VisualDashboard | null;
}

type ReportStatus = "idle" | "loading" | "loaded" | "error";

// ============================================================
// Pure helpers
// ============================================================

function formatPeriod(start: string, end: string): string {
  if (!start && !end) return "All periods";
  if (start && end) return `${start} – ${end}`;
  if (start) return `From ${start}`;
  return `Until ${end}`;
}

function todayLabel(): string {
  return new Date().toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
}

// ============================================================
// PDF generation
// ============================================================

function downloadPdf(
  report: ExecutiveReport,
  productName: string,
  period: string
): void {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const PAGE_W = 210;
  const MARGIN = 20;
  const TEXT_W = PAGE_W - MARGIN * 2;
  const dateLabel = todayLabel();

  let y = 22;

  function maybeNewPage(needed: number): void {
    if (y + needed > 274) {
      writeFooter();
      doc.addPage();
      y = 22;
    }
  }

  function writeFooter(): void {
    const page = doc.getNumberOfPages();
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by IRIP  |  Confidential  |  ${dateLabel}  |  Page ${page}`,
      MARGIN,
      288
    );
    doc.setTextColor(0, 0, 0);
  }

  function heading(text: string, size = 13, r = 24, g = 24, b = 27): void {
    maybeNewPage(size + 6);
    doc.setFontSize(size);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(r, g, b);
    doc.text(text, MARGIN, y);
    doc.setTextColor(0, 0, 0);
    y += size * 0.55 + 4;
  }

  function paragraph(text: string, size = 10): void {
    const lines = doc.splitTextToSize(text, TEXT_W) as string[];
    for (const line of lines) {
      maybeNewPage(size * 0.5 + 2);
      doc.setFontSize(size);
      doc.setFont("helvetica", "normal");
      doc.text(line, MARGIN, y);
      y += size * 0.5 + 2;
    }
    y += 2;
  }

  function bullets(items: string[], size = 10): void {
    for (const item of items) {
      const lines = doc.splitTextToSize(`• ${item}`, TEXT_W - 3) as string[];
      for (let i = 0; i < lines.length; i++) {
        maybeNewPage(size * 0.5 + 2);
        doc.setFontSize(size);
        doc.setFont("helvetica", "normal");
        doc.text(i === 0 ? lines[i] : `  ${lines[i]}`, MARGIN, y);
        y += size * 0.5 + 2;
      }
    }
    y += 2;
  }

  // ── Cover header ──────────────────────────────────────────
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(24, 24, 27);
  doc.text("IRIP — Review Intelligence Report", MARGIN, y);
  y += 9;

  doc.setFontSize(13);
  doc.setFont("helvetica", "normal");
  doc.text(productName, MARGIN, y);
  y += 6;

  doc.setFontSize(9);
  doc.setTextColor(113, 113, 122);
  doc.text(
    `Period: ${period}   |   Generated: ${dateLabel}   |   CONFIDENTIAL`,
    MARGIN,
    y
  );
  y += 8;
  doc.setTextColor(0, 0, 0);

  doc.setDrawColor(228, 228, 231);
  doc.setLineWidth(0.4);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 8;

  // ── Executive narrative ────────────────────────────────────
  if (report.executive_narrative) {
    heading("Executive Summary", 14);
    paragraph(report.executive_narrative, 10);
  }

  // ── Confidence ─────────────────────────────────────────────
  heading("Data Confidence", 12);
  paragraph(report.confidence_note, 10);

  // ── Strengths ──────────────────────────────────────────────
  if (report.key_strengths.length > 0) {
    heading("Key Strengths", 12, 22, 101, 52);
    bullets(report.key_strengths.slice(0, 4), 10);
  }

  // ── Risks ──────────────────────────────────────────────────
  if (report.key_risks.length > 0) {
    heading("Key Risks", 12, 185, 28, 28);
    bullets(report.key_risks.slice(0, 4), 10);
  }

  // ── Competitive position ───────────────────────────────────
  if (report.competitor_takeaways.length > 0) {
    heading("Competitive Position", 12);
    bullets(report.competitor_takeaways.slice(0, 3), 10);
  }

  // ── Recommended actions ────────────────────────────────────
  if (report.recommended_actions.length > 0) {
    heading("Recommended Actions", 12);
    bullets(report.recommended_actions.slice(0, 5), 10);
  }

  writeFooter();
  doc.save(
    `irip-report-${report.product_id}-${dateLabel.replace(/ /g, "-")}.pdf`
  );
}

// ============================================================
// Plain text copy
// ============================================================

function buildCopyText(
  report: ExecutiveReport,
  productName: string,
  period: string
): string {
  const sep = "─".repeat(60);
  const lines: string[] = [
    "IRIP — Review Intelligence Report",
    `Product: ${productName}`,
    `Period: ${period}`,
    "CONFIDENTIAL",
    "",
  ];

  if (report.executive_narrative) {
    lines.push("EXECUTIVE SUMMARY", sep, report.executive_narrative, "");
  }

  lines.push("KEY STRENGTHS", sep);
  for (const s of report.key_strengths.slice(0, 4)) lines.push(`• ${s}`);
  lines.push("");

  lines.push("KEY RISKS", sep);
  for (const s of report.key_risks.slice(0, 4)) lines.push(`• ${s}`);
  lines.push("");

  if (report.competitor_takeaways.length > 0) {
    lines.push("COMPETITIVE POSITION", sep);
    for (const s of report.competitor_takeaways.slice(0, 3))
      lines.push(`• ${s}`);
    lines.push("");
  }

  lines.push("RECOMMENDED ACTIONS", sep);
  for (const s of report.recommended_actions.slice(0, 5)) lines.push(`• ${s}`);
  lines.push("", `Generated by IRIP | ${new Date().toISOString()}`);

  return lines.join("\n");
}

// ============================================================
// Skeleton loading state
// ============================================================

function ReportSkeleton() {
  return (
    <div className="space-y-4 p-6">
      <div className="space-y-2">
        <Skeleton className="h-6 w-2/3" />
        <Skeleton className="h-4 w-1/3" />
        <Skeleton className="h-3 w-40" />
      </div>
      <Card>
        <CardHeader>
          <Skeleton className="h-5 w-44" />
        </CardHeader>
        <CardContent className="space-y-2">
          {[...Array(6)].map((_, i) => (
            <Skeleton
              key={i}
              className={`h-4 ${i % 3 === 2 ? "w-4/5" : "w-full"}`}
            />
          ))}
        </CardContent>
      </Card>
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
        {[...Array(4)].map((_, i) => (
          <Card key={i}>
            <CardContent className="pt-4 space-y-2">
              <Skeleton className="h-3 w-20" />
              <Skeleton className="h-7 w-14" />
            </CardContent>
          </Card>
        ))}
      </div>
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
        {[0, 1].map((i) => (
          <Card key={i}>
            <CardHeader>
              <Skeleton className="h-5 w-32" />
            </CardHeader>
            <CardContent className="space-y-2">
              {[...Array(3)].map((_, j) => (
                <Skeleton key={j} className="h-4 w-full" />
              ))}
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}

// ============================================================
// Animation preset
// ============================================================

const fadeUp = {
  initial: { opacity: 0, y: 16 },
  animate: { opacity: 1, y: 0 },
} as const;

// ============================================================
// Main component
// ============================================================

export default function ReportView({
  productId,
  competitorId,
  startDate,
  endDate,
  productName,
  dashboard,
}: ReportViewProps) {
  const [status, setStatus] = useState<ReportStatus>("idle");
  const [report, setReport] = useState<ExecutiveReport | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const period = formatPeriod(startDate, endDate);

  async function handleGenerate(): Promise<void> {
    if (!productId) return;
    setStatus("loading");
    setError(null);
    try {
      const params: WorkspaceParams = {
        product_id: productId,
        competitor_product_id: competitorId || undefined,
        start_date: startDate || undefined,
        end_date: endDate || undefined,
      };
      const result = await fetchReportWithNarrative(params);
      setReport(result);
      setStatus("loaded");
    } catch (err) {
      setError(
        err instanceof Error ? err.message : "Report generation failed."
      );
      setStatus("error");
    }
  }

  function handleDownload(): void {
    if (!report) return;
    downloadPdf(report, productName || productId, period);
  }

  async function handleCopy(): Promise<void> {
    if (!report) return;
    const text = buildCopyText(report, productName || productId, period);
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  }

  // ── Idle / error with no data ─────────────────────────────
  if (status === "idle" || (status === "error" && !report)) {
    return (
      <div className="flex flex-col items-center justify-center min-h-96 gap-5 p-8">
        <div className="rounded-full bg-zinc-100 p-5">
          <FileText size={34} className="text-zinc-500" />
        </div>
        <div className="text-center space-y-1.5 max-w-xs">
          <h2 className="text-lg font-semibold text-zinc-900">
            Generate AI Report
          </h2>
          <p className="text-sm text-zinc-500 leading-relaxed">
            Gemini writes a professional 4-paragraph intelligence brief from
            your product data. Takes 3–5 seconds.
          </p>
          {status === "error" && error && (
            <p className="text-sm text-red-600 flex items-center gap-1.5 justify-center pt-1">
              <AlertCircle size={13} />
              {error}
            </p>
          )}
        </div>
        <Button
          onClick={() => void handleGenerate()}
          disabled={!productId}
        >
          Generate Report
        </Button>
        {!productId && (
          <p className="text-xs text-zinc-400">Select a product first</p>
        )}
      </div>
    );
  }

  // ── Loading ───────────────────────────────────────────────
  if (status === "loading") {
    return (
      <div>
        <div className="flex items-center gap-2 px-6 pt-5 pb-1 text-sm text-zinc-500">
          <Loader2 size={13} className="animate-spin" />
          Gemini is writing your report…
        </div>
        <ReportSkeleton />
      </div>
    );
  }

  // ── Loaded ────────────────────────────────────────────────
  if (status === "loaded" && report) {
    const kpiCards: KpiCard[] = (dashboard?.kpi_cards ?? []).slice(0, 4);

    return (
      <div className="space-y-4 p-6">
        {/* Action bar */}
        <div className="flex items-center justify-between flex-wrap gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={() => void handleGenerate()}
          >
            <Loader2 size={12} />
            Regenerate
          </Button>
          <div className="flex gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={() => void handleCopy()}
            >
              {copied ? (
                <CheckCircle2 size={13} className="text-green-600" />
              ) : (
                <Copy size={13} />
              )}
              {copied ? "Copied!" : "Copy as Text"}
            </Button>
            <Button size="sm" onClick={handleDownload}>
              <Download size={13} />
              Download PDF
            </Button>
          </div>
        </div>

        {/* Report header card */}
        <motion.div {...fadeUp} transition={{ duration: 0.28 }}>
          <Card>
            <CardContent className="pt-5 pb-4">
              <div className="flex items-start justify-between gap-4 flex-wrap">
                <div>
                  <p className="text-xs font-medium text-zinc-400 uppercase tracking-wider mb-1">
                    IRIP — Review Intelligence Platform
                  </p>
                  <h2 className="text-xl font-bold text-zinc-900 leading-tight">
                    {productName || productId}
                  </h2>
                  <p className="text-sm text-zinc-500 mt-0.5">
                    {period} · Generated {todayLabel()}
                  </p>
                </div>
                <Badge variant="outline" className="text-xs shrink-0">
                  Confidential
                </Badge>
              </div>
            </CardContent>
          </Card>
        </motion.div>

        {/* Gemini executive narrative */}
        {report.executive_narrative ? (
          <motion.div
            {...fadeUp}
            transition={{ duration: 0.28, delay: 0.07 }}
          >
            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-base">Executive Summary</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-zinc-700 leading-relaxed whitespace-pre-line">
                  {report.executive_narrative}
                </p>
              </CardContent>
            </Card>
          </motion.div>
        ) : (
          <motion.div
            {...fadeUp}
            transition={{ duration: 0.28, delay: 0.07 }}
          >
            <Card className="border-dashed">
              <CardContent className="pt-4 pb-3">
                <p className="text-xs text-zinc-400">
                  AI narrative not available — Gemini may be disabled or
                  IRIP_LLM_MODE is set to "off".
                </p>
              </CardContent>
            </Card>
          </motion.div>
        )}

        {/* Key metrics row */}
        {kpiCards.length > 0 && (
          <motion.div
            {...fadeUp}
            transition={{ duration: 0.28, delay: 0.14 }}
          >
            <p className="text-xs font-semibold text-zinc-400 uppercase tracking-wide mb-2">
              Key Metrics
            </p>
            <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
              {kpiCards.map((card) => (
                <Card key={card.id}>
                  <CardContent className="pt-4 pb-3">
                    <p className="text-xs text-zinc-500 mb-1">{card.label}</p>
                    <p className="text-lg font-bold text-zinc-900">
                      {card.value ?? "—"}
                    </p>
                    {card.helper_text && (
                      <p className="text-xs text-zinc-400 mt-0.5 truncate">
                        {card.helper_text}
                      </p>
                    )}
                  </CardContent>
                </Card>
              ))}
            </div>
          </motion.div>
        )}

        {/* Top insights: praise + complaints */}
        <motion.div
          {...fadeUp}
          transition={{ duration: 0.28, delay: 0.21 }}
          className="grid grid-cols-1 gap-3 sm:grid-cols-2"
        >
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm text-green-700">
                Top Praises
              </CardTitle>
            </CardHeader>
            <CardContent>
              <ul className="space-y-2">
                {report.key_strengths.slice(0, 3).map((item, i) => (
                  <li key={i} className="flex gap-2 text-sm text-zinc-700">
                    <span className="mt-0.5 shrink-0 text-green-500 font-bold">
                      ✓
                    </span>
                    <span>{item}</span>
                  </li>
                ))}
                {report.key_strengths.length === 0 && (
                  <li className="text-sm text-zinc-400">
                    No praise signals yet.
                  </li>
                )}
              </ul>
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm text-red-700">
                Top Complaints
              </CardTitle>
            </CardHeader>
            <CardContent>
              <ul className="space-y-2">
                {report.key_risks.slice(0, 3).map((item, i) => (
                  <li key={i} className="flex gap-2 text-sm text-zinc-700">
                    <span className="mt-0.5 shrink-0 text-red-400 font-bold">
                      !
                    </span>
                    <span>{item}</span>
                  </li>
                ))}
                {report.key_risks.length === 0 && (
                  <li className="text-sm text-zinc-400">
                    No risk signals yet.
                  </li>
                )}
              </ul>
            </CardContent>
          </Card>
        </motion.div>

        {/* Competitive position */}
        {report.competitor_takeaways.length > 0 && (
          <motion.div
            {...fadeUp}
            transition={{ duration: 0.28, delay: 0.27 }}
          >
            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-base">
                  Competitive Position
                </CardTitle>
              </CardHeader>
              <CardContent>
                <ul className="space-y-2">
                  {report.competitor_takeaways.slice(0, 4).map((item, i) => (
                    <li key={i} className="flex gap-2 text-sm text-zinc-700">
                      <span className="mt-0.5 shrink-0 text-zinc-400">→</span>
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          </motion.div>
        )}

        {/* Recommended actions */}
        {report.recommended_actions.length > 0 && (
          <motion.div
            {...fadeUp}
            transition={{ duration: 0.28, delay: 0.33 }}
          >
            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-base">
                  Recommended Actions
                </CardTitle>
              </CardHeader>
              <CardContent>
                <ol className="space-y-2 list-decimal list-inside">
                  {report.recommended_actions.slice(0, 5).map((item, i) => (
                    <li key={i} className="text-sm text-zinc-700">
                      {item}
                    </li>
                  ))}
                </ol>
              </CardContent>
            </Card>
          </motion.div>
        )}

        {/* Confidence note */}
        <motion.div
          {...fadeUp}
          transition={{ duration: 0.28, delay: 0.38 }}
        >
          <Card className="border-dashed">
            <CardContent className="pt-4 pb-3">
              <p className="text-xs text-zinc-400 leading-relaxed">
                <strong className="text-zinc-500">Data confidence:</strong>{" "}
                {report.confidence_note}
              </p>
            </CardContent>
          </Card>
        </motion.div>
      </div>
    );
  }

  return null;
}
